### ISSUE TITLE
Issue with nan.h on windows (build fails)

### ISSUE THREAD

**Issue by dadleyy** [xmppo/node-expat#78]
I was having an issue where during the node-gyp rebuild process on my windows machine:

> ..\node-expat.cc(1): fatal error C1083: Cannot open include file: 'nan.h': No such file..

After running `npm install nan --save` I was still getting the issue, so I went into `node-expat.cc` and changed the include to be a relative path:

```
#include "node_modules/nan/nan.h"
```

Now everything is working fine. 

It seems like this is more of an issue with `node-gyp` not updating the `include_dirs` in the build process on windows machines properly. Just wanted to make anyone who runs into this aware.

**Comment by jainsahab** [comment]
I got `fatal error C1060: compiler is out of heap space `. any idea regarding this error ?

**Comment by jeanru** [comment]
I had fatal error C1083:  
\ucrt\corecrt.h(10): fatal error C1083: �޷��򿪰����ļ�: ��vcruntime.h��: No such file or directory (..\..\..\deps\libexpat\lib\xmlrole.c) [c:\Users\leon\AppData\Roaming\npm-cache\node_modules\node-expat\build\deps\libexpat\expat.vcxproj]
